### PR TITLE
Supports definition file.

### PR DESCRIPTION
**Pull request by sromerotech**
Hi, I've added the option to mount the `definition.json` file in order to load it. I'll appreciate any feedback on it. Thank you in advance.

### CODE REVIEW

**Comment by Namoshek** [comment]
Thank you for the PR, it looks good so far!

One thing I'm not sure about is the requirement of a management image. I'll dive into this in the evening and let you know.

**Comment by Namoshek** [comment]
I renamed all occurences of `definition` to `definitions` (since this seems to be the official naming and for consistency). I also moved the sample `definitions.json` used in the test pipeline to the `.ci` directory to clearify its use. The test pipeline itself does run also with the `definitions` option set for other images, so we need no extra pipeline I guess.

I really like your implementation in `entrypoint.sh` using `RABBITMQ_SERVER_ADDITIONAL_ERL_ARGS` to set the option for the definitions file. Saves adding a custom `rabbitmq.conf` just for the option. Nice work and thanks again!

**Comment by Namoshek** [comment]
Released as [`v1.1.0`](https://github.com/Namoshek/rabbitmq-github-action/releases/tag/v1.1.0).

**Comment by Namoshek** [comment]
Almost forgot...

> One thing I'm not sure about is the requirement of a management image.

The way this is described in the [Schema Definition Export and Import](https://www.rabbitmq.com/definitions.html) part of the documentation, I assumed that `load_definitions` is now part of the core. Turns out, it is not. It requires the `rabbitmq_management` plugin to be enabled, which can be done manually or by using a suitable image tag. I therefore changed the description to contain both options.

Because the option seems to be ignored if the management plugin is not enabled, it doesn't hurt if we always pass a definitions file in our test pipeline. 👍

**Comment by sromerotech** [comment]
> I renamed all occurences of `definition` to `definitions` (since this seems to be the official naming and for consistency). I also moved the sample `definitions.json` used in the test pipeline to the `.ci` directory to clearify its use. The test pipeline itself does run also with the `definitions` option set for other images, so we need no extra pipeline I guess.

Wonderful, thank you for the improvements. it's been a pleasure :smile:

**Pull request merged**
